apiVersion: ops.aditya.dev/v1alpha1
kind: MustHaveConfig
metadata:
  labels:
    app.kubernetes.io/name: musthaveconfig
    app.kubernetes.io/instance: musthaveconfig-sample
    app.kubernetes.io/part-of: musthaveconfig-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: musthaveconfig-operator
  name: musthaveconfig-sample
spec:
  # TODO(user): Add fields here
